<?php
$currencies = array('MYR', 'SGD', 'AUD', 'HKD', 'USD', 'EUR');

$emp_descs = array('Local Non-listed Company (less than 1000 staffs)',
                   'Local Listed Company (less than 1000 staffs)', 
                   'Local Non-listed Company (1000 or more staffs)',
                   'Local Listed Company (1000 or more staffs)', 
                   'Multi National Company (not Fortune 500)', 
                   'Multi National Company (Fortune 500)');
?>
