<?php
/**
 * This configuration file can be modified at will by adding
 * more currencies. 
 */

// default - MYR 
$subscriptions_rates = array(
    'MYR' => array(
        '1' => 1000,
        '3' => 1500,
        '6' => 2000,
        '9' => 2500,
        '12' => 3000
    ),
    'SGD' => array(
        '1' => 500,
        '3' => 1000,
        '6' => 1500,
        '9' => 2000,
        '12' => 2500
    )
);
?>
