<?php
/**
 * This configuration file can be modified at will by adding
 * more currencies. 
 */

// subscriptions default - MYR 
$subscriptions_rates = array(
    'MYR' => array(
        '4' => 3000,
        '8' => 5000,
        '12' => 6500
    ),
    'SGD' => array(
        '4' => 2500,
        '8' => 4500,
        '12' => 6000
    )
);

// postings default - MYR
$postings_rates = array(
    'MYR' => 150,
    'SGD' => 100
);
?>
