<?php
require_once dirname(__FILE__). "/../private/lib/utilities.php";

/*
    Generate the seed and return the ID and SEED in XML format. 
    A seed and a seed id are required for web-based authentication.
    The SHA1 hash is generated by concatenating id, md5(password) and seed. 
*/
header('Content-type: text/xml');
$xml_dom = new XMLDOM ();
$response = array();

/*if (empty($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == 'off') {
    $response['errors'] = array(
        'error' => 'insecure'
    );
    echo $xml_dom->get_xml_from_array($response);
    exit();
}
*/
$mysqli = Database::connect();
list($usec, $sec) = explode(" ", microtime());
$seed = number_format(($usec + $sec), 8, ".", "");
$query = "INSERT INTO seeds SET seed = '". $seed. "'";

if ($mysqli->execute($query)) {
    $query = "SELECT id, seed FROM seeds ORDER BY id DESC LIMIT 1";
    if ($result = $mysqli->query($query)) {
        $response = array(
            'login' => array(
                'id' => $result[0]['id'],
                'seed' => $result[0]['seed']
            )
        );
        echo $xml_dom->get_xml_from_array($response);
        exit();
    }        
}

// Return an error XML if there is a problem. 
echo $mysqli->error_in_xml();

?>